import Head from "next/head";
import Navbar from "./components/Navbar";
import Carrousel from "./components/Carrousel";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>New app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Carrousel />
      </main>
    </div>
  );
}
